# Generated by Django 5.2.10 on 2026-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(default=1),
        ),
    ]
