# Generated by Django 5.2.10 on 2026-02-02 22:20
# Fixed: Removed AddField operations for fields already in 0001_initial

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0001_initial'),
    ]

    operations = [
        # All fields (last_login, is_active, is_staff, is_superuser) are
        # already included in 0001_initial.py, so no operations needed here.
    ]
