# Generated by Django 5.2.10 on 2026-02-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0002_add_django_user_fields'),
    ]

    operations = [
        # Rename project_id CharField to project ForeignKey
        # Since we're using db_column='project_id', no actual database change happens
        migrations.RenameField(
            model_name='ticket',
            old_name='project_id',
            new_name='project',
        ),
        # Now alter it to be a ForeignKey
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(on_delete=models.CASCADE, to='wintermute.project', db_column='project_id'),
        ),
    ]
