# Generated by Django 5.2.10 on 2026-02-03 01:40

import wintermute.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0004_user_proper_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=wintermute.models.auth.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
