# Generated by Django 5.2.10 on 2026-02-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0005_user_id_auto_uuid'),
    ]

    operations = [
        migrations.DeleteModel(name='ApiToken',),
    ]
