# Generated by Django 5.2.10 on 2026-02-03 02:36

import wintermute.models.agents
import wintermute.models.auth
import wintermute.models.infrastructure
import wintermute.models.projects
import wintermute.models.sessions
import wintermute.models.sources
import wintermute.models.supervisor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0006_remove_apitoken_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(default=wintermute.models.agents.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agentmetricslog',
            name='id',
            field=models.CharField(default=wintermute.models.agents.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='id',
            field=models.CharField(default=wintermute.models.agents.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='id',
            field=models.CharField(default=wintermute.models.agents.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agentwake',
            name='id',
            field=models.CharField(default=wintermute.models.sessions.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.CharField(default=wintermute.models.sessions.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='columnpreference',
            name='id',
            field=models.CharField(default=wintermute.models.auth.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=wintermute.models.projects.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='id',
            field=models.CharField(default=wintermute.models.auth.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuesource',
            name='id',
            field=models.CharField(default=wintermute.models.sources.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='id',
            field=models.CharField(default=wintermute.models.agents.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=wintermute.models.projects.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remotetoken',
            name='id',
            field=models.CharField(default=wintermute.models.sources.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporesource',
            name='id',
            field=models.CharField(default=wintermute.models.projects.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionfile',
            name='id',
            field=models.CharField(default=wintermute.models.sessions.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionfileconfig',
            name='id',
            field=models.CharField(default=wintermute.models.sessions.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionfiledefinition',
            name='id',
            field=models.CharField(default=wintermute.models.sessions.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='id',
            field=models.CharField(default=wintermute.models.projects.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supervisorstate',
            name='id',
            field=models.CharField(default=wintermute.models.supervisor.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasksource',
            name='id',
            field=models.CharField(default=wintermute.models.supervisor.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=wintermute.models.projects.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='id',
            field=models.CharField(default=wintermute.models.projects.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vmtarget',
            name='id',
            field=models.CharField(default=wintermute.models.infrastructure.generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
