# Generated by Django 5.2.10 on 2026-02-03 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('wintermute', '0007_id_fields_autogenerate_editable_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_token',
            field=models.ForeignKey(
                blank=True,
                help_text='API token for this agent to authenticate with Wintermute',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agents',
                to='authtoken.token'
            ),
        ),
    ]
