# Generated by Django 5.2.10 on 2026-02-03 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0008_agent_api_token_fk'),
    ]

    operations = [
        # Rename the field but keep same db_column - this tells Django ORM the new name
        # while preserving the existing column and data
        migrations.RenameField(
            model_name='agent',
            old_name='vm_target_id',
            new_name='vm_target',
        ),
        # Now alter the field to be a proper FK
        migrations.AlterField(
            model_name='agent',
            name='vm_target',
            field=models.ForeignKey(
                blank=True,
                db_column='vm_target_id',
                help_text='VM target where this agent runs',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agents',
                to='wintermute.vmtarget'
            ),
        ),
        # Convert autostart from Integer to Boolean
        migrations.AlterField(
            model_name='agent',
            name='autostart',
            field=models.BooleanField(default=False),
        ),
    ]
