# Generated by Django 5.2.10 on 2026-02-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wintermute', '0009_agent_vm_target_fk_autostart_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesource',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
